# Schema for the configuration files of the CKEditor CodeMirror module.

ckeditor.plugin.ckeditor_axe:
  type: config_object
  label: 'CKEditor AXE settings'
  mapping:
    excluded_rules:
      type: sequence
      label: 'Accessibility Excluded Rules'
      sequence:
        type: string
        label: 'Rule'
    tags:
      type: mapping
      label: 'Accessibility Standard/Purpose'
      mapping:
        wcag2a:
          type: boolean
          label: 'WCAG 2.0 Level A'
        wcag2aa:
          type: boolean
          label: 'WCAG 2.0 Level AA'
        wcag21aa:
          type: boolean
          label: 'WCAG 2.1 Level AA'
        section508:
          type: boolean
          label: 'Section 508'
        best-practice:
          type: boolean
          label: 'Best practices endorsed by Deque'
        experimental:
          type: boolean
          label: 'Cutting-edge techniques'
